config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :lists, only: [:index, :show, :new, :create] do
  #   resources :movies, only: [:create]
  #   resources :bookmarks, only: [:destroy, :new, :create]
  # end

  root to: "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end


end

# BookmarksController
#   GET new
#     assigns a new bookmark to @bookmark (FAILED - 1)
#   POST create
#     with valid params
#       creates a new bookmark (FAILED - 2)
#       assigns a newly created bookmark as @bookmark (FAILED - 3)
#       redirects to the created list (FAILED - 4)
#     with invalid params
#       assigns a newly created but unsaved bookmark as @bookmark (FAILED - 5)
#       re-renders the 'new' template or 'lists/show' (FAILED - 6)
#   DELETE destroy
#     deletes a bookmark (FAILED - 7)

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @lists = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end


#   GET show
#     assigns the requested list as @list (FAILED - 8)
#   GET new
#     assigns a new list as @list (FAILED - 9)
#   POST create
#     with valid params
#       creates a new List (FAILED - 10)
#       assigns a newly created list as @list (FAILED - 11)
#       redirects to the created list (FAILED - 12)
#     with invalid params
#       assigns a newly created but unsaved list as @list (FAILED - 13)
#       re-renders the 'new' template (FAILED - 14)

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/bookmars_helper.rb
module BookmarsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_modal.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>

      <%= simple_form_for [list, bookmark] do |f| %>
        <div class="modal-body">
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: "tom-select" } } %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Add movie", class: "btn btn-flat" %>
          <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie, prompt: "Select a movie", input_html: {data: { controller: "tom-select"}} %>
          <%= f.submit class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>All list</h1>
      <ul class="list-group mb-3">
          <% @lists.each do |list| %>
          <li class="list-group-item">
            <%= link_to list.name, list_path(list) %>
          </li>
        <% end %>
      </ul>
      <%= link_to "Add a new list", new_list_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<%# <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create a new list</h1>
      <%= simple_form_for @list do |f| %>
        <%# <%= f.input :name %>
        <%# <%= f.submit class: 'btn btn-primary' %>
      <%# <% end %>
    <%# </div> %>
  <%# </div> %>
<%# </div> %>

<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Drama' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%# <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1><%= @list.name %>

      <%# <%= link_to "See all lists", lists_path %>
    <%# </div> %>
  <%# </div> %>
<%# </div> %>


<div class="position-relative">
  <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('list_background.jpg') %>)">
    <h1><%= @list.name %></h1>
  </div>
  <span class="movie-tag"><%= pluralize(@list.movies.size, "movie") %></span>
</div>
<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>
    <div>
      <button type="button" class="btn btn-flat" data-bs-toggle="modal" data-bs-target="#new_movie_modal">
        add a movie
      </button>
      <%= link_to "delete this list", list_path(@list), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
    </div>
  </div>
  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render "bookmarks/modal", list: @list, bookmark: @bookmark %>

app/views/movies/index.html.erb
<h1>movies</h1>

<% @movies.each do |movie| %>
  <li >
   <%= movie.title %>
  </li>
<% end %>